import datetime
from pathlib import Path

from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE

import main_recovery_step14 as s14
import main_recovery_step13 as s13
import main_recovery_step12 as s12
import main_recovery_step10 as s10
import main_v319 as v319
import main_v310 as v310

base=s14.base
N=v310.N


# -----------------------------------------------------------------------------
# Project/detail-page detection
# -----------------------------------------------------------------------------
def _project_parts(d):
    return (
        s13._k(s13._customer_task(d)),
        s13._k(d.get('task_name')),
        s13._k(d.get('customer')),
    )


def _project_score(sl,d):
    q=s13._k(s13._slide_text(sl))
    full,task,customer=_project_parts(d)
    if full and full in q:
        return 160
    if task and customer and task in q and customer in q:
        return 145
    # The user requested that the detail section be found primarily by 과제명.
    if task and task in q:
        return 120
    return 0


def _summary_indices(prs):
    return {si for si,_,_ in s14._summary_pages(prs)}


def _is_detail_like(sl):
    # Do not require an exact old template. Existing pages may have been rearranged.
    text=s13._slide_text(sl)
    q=s13._k(text)
    d_hits=sum(1 for token in ('2d','3d','4d','5d','6d') if token in q)
    meta_hits=sum(1 for token in ('signal','이슈기인','발생단계') if token in q)
    return d_hits>=3 or (d_hits>=2 and meta_hits>=1)


def _project_detail_indices(prs,d):
    summaries=_summary_indices(prs)
    return [i for i,sl in enumerate(prs.slides)
            if i not in summaries and _is_detail_like(sl) and _project_score(sl,d)>=120]


def _find_existing_detail(prs,d):
    pages=_project_detail_indices(prs,d)
    if not pages:
        return None
    issue=s13._k(s13._issue_display(d))
    best=None
    for i in pages:
        text=s13._slide_text(prs.slides[i])
        q=s13._k(text)
        score=_project_score(prs.slides[i],d)
        score+=s13._detail_structure_score(prs.slides[i])*4
        if issue and issue in q:
            score+=150
        else:
            from difflib import SequenceMatcher
            ratios=[SequenceMatcher(None,issue,s13._k(x)).ratio()
                    for x in text.splitlines() if s13._k(x)] if issue else []
            if ratios:
                score+=int(70*max(ratios))
        if best is None or score>best[0]:
            best=(score,i)
    return best[1] if best and best[0]>=245 else None


def _new_detail_position(prs,d):
    pages=_project_detail_indices(prs,d)
    return max(pages)+1 if pages else len(prs.slides)


# -----------------------------------------------------------------------------
# Clone another real detail page ONLY as a layout shell.
# All old issue-specific text/images in the 2D~6D work area are cleared before
# current 8D data is rendered, so another project's content cannot be duplicated.
# -----------------------------------------------------------------------------
def _template_detail_index(prs,d):
    summaries=_summary_indices(prs)
    same=_project_detail_indices(prs,d)
    if same:
        # Best visual match is normally the latest page in the same project section.
        return same[-1]

    candidates=[]
    for i,sl in enumerate(prs.slides):
        if i in summaries or not _is_detail_like(sl):
            continue
        structure=s13._detail_structure_score(sl)
        # Prefer pages containing the standard metadata labels and the most D blocks.
        q=s13._k(s13._slide_text(sl))
        meta=sum(1 for x in ('signal','이슈기인','발생단계') if x in q)
        candidates.append((structure*10+meta*8,i))
    if not candidates:
        raise ValueError('주간회의 PPT에서 복제할 수 있는 2D~6D 상세 페이지 양식을 찾지 못했습니다.')
    candidates.sort(reverse=True)
    return candidates[0][1]


def _overlap_ratio(sh,zone):
    try:
        x=float(sh.left)/v310.EMU; y=float(sh.top)/v310.EMU
        w=float(sh.width)/v310.EMU; h=float(sh.height)/v310.EMU
    except Exception:
        return 0.0
    zx,zy,zw,zh=zone
    ix=max(0,min(x+w,zx+zw)-max(x,zx))
    iy=max(0,min(y+h,zy+zh)-max(y,zy))
    inter=ix*iy
    area=max(w*h,1e-6)
    return inter/area


def _content_zones():
    # Slightly expanded compared with the render boxes to catch old text and photos.
    return [
        (.38,2.35,5.05,1.30),
        (.38,3.72,5.05,1.50),
        (.38,5.18,5.05,2.05),
        (5.58,2.30,5.10,1.25),
        (5.58,3.56,5.10,2.10),
        (5.58,5.72,5.10,1.25),
    ]


def _static_detail_label(text):
    q=s13._k(text)
    static={
        '2d','3d','4d','5d','6d','7d',
        '현상','임시대책필요시','원인분석','개선대책','유효성점검','수평전개',
        'signal','이슈기인','발생단계'
    }
    return q in static


def _clear_cloned_issue_content(sl):
    # First remove anything generated by a prior automation run.
    v310.remove_previous_auto(sl)
    zones=_content_zones()

    for sh in list(sl.shapes):
        # Preserve native marker/title groups. Their inner old content is structural.
        if getattr(sh,'shape_type',None)==MSO_SHAPE_TYPE.GROUP:
            continue

        in_work_area=any(_overlap_ratio(sh,z)>=0.35 for z in zones)
        if not in_work_area:
            continue

        # Old issue photos in 2D~6D must not survive the clone.
        if getattr(sh,'shape_type',None)==MSO_SHAPE_TYPE.PICTURE:
            try:
                sh._element.getparent().remove(sh._element)
            except Exception:
                pass
            continue

        # Keep the real shape/border/layout, but erase the other project's text.
        # Exact D labels/titles are retained when they are ungrouped in the source.
        if hasattr(sh,'text_frame'):
            old=N(getattr(sh,'text',''))
            if old and not _static_detail_label(old):
                try:
                    sh.text=''
                except Exception:
                    try: sh.text_frame.clear()
                    except Exception: pass


def _clone_detail_shell(prs,d,insert_at):
    template_index=_template_detail_index(prs,d)
    s13._clone_slide_with_rels(prs,template_index)
    s13._move_last_slide_to(prs,insert_at)
    sl=prs.slides[insert_at]
    _clear_cloned_issue_content(sl)
    return sl,template_index


# -----------------------------------------------------------------------------
# Weekly update
# -----------------------------------------------------------------------------
def weekly_fix3(src,out,d,g,mode):
    prs=Presentation(src)
    _,_,summary_action=s14._update_summary_by_task(prs,d,g,mode)

    target=_find_existing_detail(prs,d) if mode=='existing' else None
    detail_action='업데이트'

    if target is None:
        insert_at=_new_detail_position(prs,d)
        _,template_index=_clone_detail_shell(prs,d,insert_at)
        target=insert_at
        detail_action=f'기존 상세 양식 복제 후 내용 초기화/신규 작성 (원본 slide {template_index+1})'

    # Reuse all currently validated rendering/header/signal/origin behavior.
    s13._update_detail_slide(prs.slides[target],d,g,mode)

    Path(out).parent.mkdir(parents=True,exist_ok=True)
    try:
        prs.save(out); saved=out
    except PermissionError:
        p=Path(out)
        saved=str(p.with_name(p.stem+'_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S')+p.suffix))
        prs.save(saved)

    return ('주간회의 PPT: 요약 '+summary_action+' / 상세 '+detail_action+
            f' (과제명={N(d.get("task_name"))})',saved)


base.weekly=weekly_fix3


class RecoveryStep14Fix3App(s10.RecoveryStep10App):
    def __init__(self):
        super().__init__()
        self.title('8D 이슈 자동화 v3.2.0 RECOVERY STEP14 FIX3')


if __name__=='__main__':
    RecoveryStep14Fix3App().mainloop()
